pub(super) const DUPLICATE_STATE_PHRASES: &[&str] = &[
    "duplicate/no-active-work",
    "no-active-work",
    "no active work",
    "duplicate pr",
    "duplicate issue",
    "duplicate lane",
];
pub(super) const DUPLICATE_STATE_TARGETS: &[&str] = &[
    "pr #",
    "pull request #",
    "issue #",
    "github state",
    "current issue",
    "current pr",
    "current pull request",
];
pub(super) const DUPLICATE_STATE_CHECKS: &[&str] = &[
    "re-check",
    "rechecked",
    "re-checked",
    "checked",
    "confirmed",
    "current github state",
    "after current",
];
pub(super) const CODEXY_CONTRACT_PHRASES: &[&str] = &[
    "@codexy",
    "$orchestration",
    "active codexy workflow",
    "active codexy plugin workflow",
    "preserve codexy workflow",
    "preserved codexy workflow",
    "routes through $orchestration",
    "route through $orchestration",
];
pub(super) const OWNERSHIP_BOUNDARY_PHRASES: &[&str] = &[
    "child-owned",
    "child owned",
    "parent orchestrator",
    "parent monitors",
    "parent monitor",
    "who may edit",
    "who may only orchestrate",
    "only orchestrate",
    "receive edits",
];
pub(super) const NEGATED_CONTRACT_PHRASES: &[&str] = &[
    "not captured",
    "not active",
    "not available",
    "not preserved",
    "was not preserved",
    "no active @codexy",
    "no active codexy workflow",
    "missing",
    "omitted",
    "without @codexy",
    "without codexy",
];
pub(super) const PLANNED_CODEXY_CONTRACT_PHRASES: &[&str] = &[
    "should be restored",
    "should be preserved",
    "to be restored",
    "to be preserved",
    "will be restored",
    "will be preserved",
    "needs to be restored",
    "needs to be preserved",
];
pub(super) const NEGATED_DUPLICATE_STATE_PHRASES: &[&str] = &[
    "not captured",
    "not checked",
    "not re-checked",
    "not preserved",
    "was not preserved",
    "did not check",
    "missing",
    "omitted",
    "without checking",
    "no duplicate/no-active-work state was captured",
    "no duplicate state was captured",
    "no no-active-work state was captured",
];
pub(super) const PLANNED_DUPLICATE_STATE_PHRASES: &[&str] = &[
    "should be checked",
    "should be re-checked",
    "to be checked",
    "to be re-checked",
    "will be checked",
    "will be re-checked",
    "needs to be checked",
    "needs to be re-checked",
];
pub(super) const NEGATED_OWNERSHIP_BOUNDARY_PHRASES: &[&str] = &[
    "not captured",
    "not available",
    "not preserved",
    "was not preserved",
    "missing",
    "omitted",
    "without boundary",
    "without ownership",
    "no parent/child ownership boundary was captured",
    "no parent-child ownership boundary was captured",
    "no ownership boundary was captured",
];
pub(super) const PLANNED_OWNERSHIP_BOUNDARY_PHRASES: &[&str] = &[
    "should be captured",
    "should be preserved",
    "to be captured",
    "to be preserved",
    "will be captured",
    "will be preserved",
    "needs to be captured",
    "needs to be preserved",
];
pub(super) const PLANNED_STOP_CONDITION_PHRASES: &[&str] = &[
    "should stop",
    "should be checked",
    "should be captured",
    "should be preserved",
    "to be checked",
    "to be captured",
    "to be preserved",
    "will be checked",
    "will be captured",
    "will be preserved",
];
