use super::Expected;

pub(super) const EXPECTED: &[Expected] = &[
    Expected {
        id: "install-all",
        command: "install",
        operands: &[],
        before: &[],
        after: &["core", "github", "devtools"],
        outcome: "completed",
        error: None,
    },
    Expected {
        id: "install-core",
        command: "install",
        operands: &["core"],
        before: &[],
        after: &["core"],
        outcome: "completed",
        error: None,
    },
    Expected {
        id: "install-github",
        command: "install",
        operands: &["github"],
        before: &[],
        after: &["core", "github"],
        outcome: "completed",
        error: None,
    },
    Expected {
        id: "install-devtools",
        command: "install",
        operands: &["devtools"],
        before: &[],
        after: &["core", "devtools"],
        outcome: "completed",
        error: None,
    },
    Expected {
        id: "install-github-devtools",
        command: "install",
        operands: &["github", "devtools"],
        before: &[],
        after: &["core", "github", "devtools"],
        outcome: "completed",
        error: None,
    },
    Expected {
        id: "install-is-additive",
        command: "install",
        operands: &["github"],
        before: &["core", "devtools"],
        after: &["core", "github", "devtools"],
        outcome: "completed",
        error: None,
    },
    Expected {
        id: "update-preserves",
        command: "update",
        operands: &[],
        before: &["core", "devtools"],
        after: &["core", "devtools"],
        outcome: "completed",
        error: None,
    },
    Expected {
        id: "update-explicit-preserves",
        command: "update",
        operands: &["github"],
        before: &["core", "github", "devtools"],
        after: &["core", "github", "devtools"],
        outcome: "completed",
        error: None,
    },
    Expected {
        id: "remove-github",
        command: "remove",
        operands: &["github"],
        before: &["core", "github", "devtools"],
        after: &["core", "devtools"],
        outcome: "completed",
        error: None,
    },
    Expected {
        id: "reject-remove-core",
        command: "remove",
        operands: &["core"],
        before: &["core", "github"],
        after: &["core", "github"],
        outcome: "rejected",
        error: Some("dependency-protected-removal"),
    },
    Expected {
        id: "remove-core-with-dependent",
        command: "remove",
        operands: &["core", "github"],
        before: &["core", "github"],
        after: &[],
        outcome: "completed",
        error: None,
    },
    Expected {
        id: "reject-unknown-component",
        command: "install",
        operands: &["unknown"],
        before: &[],
        after: &[],
        outcome: "rejected",
        error: Some("unknown-component"),
    },
    Expected {
        id: "rollback-failed-install",
        command: "install",
        operands: &["devtools"],
        before: &["core", "github"],
        after: &["core", "github"],
        outcome: "rolled-back",
        error: Some("operation-failed"),
    },
    Expected {
        id: "bootstrap-default",
        command: "bootstrap",
        operands: &[],
        before: &[],
        after: &["core", "github", "devtools"],
        outcome: "completed",
        error: None,
    },
];
