pub(in super::super) const EXTERNAL_FAILURE: &[&str] = &[
    "required checks are failing",
    "required checks failed",
    "required status checks are failing",
    "status checks are failing",
    "status checks failed",
];

pub(in super::super) const FAILURE_WORDS: &[&str] = &["failed", "failure"];

pub(in super::super) const FALSE_CHECK_LABEL: &[&str] = &[
    "required checks are failing: no",
    "required status checks are failing: no",
    "status checks are failing: no",
    "required checks failed: no",
    "required status checks failed: no",
    "status checks failed: no",
    "required checks are failing: false",
    "required status checks are failing: false",
    "status checks are failing: false",
    "required checks failed: false",
    "required status checks failed: false",
    "status checks failed: false",
    "required checks are failing: none",
    "required status checks are failing: none",
    "status checks are failing: none",
    "required checks failed: none",
    "required status checks failed: none",
    "status checks failed: none",
    "required checks are failing? no",
    "required status checks are failing? no",
    "status checks are failing? no",
    "required checks failed? no",
    "required status checks failed? no",
    "status checks failed? no",
    "required checks are failing? false",
    "required status checks are failing? false",
    "status checks are failing? false",
    "required checks failed? false",
    "required status checks failed? false",
    "status checks failed? false",
    "required checks are failing? none",
    "required status checks are failing? none",
    "status checks are failing? none",
    "required checks failed? none",
    "required status checks failed? none",
    "status checks failed? none",
    "required checks are failing = no",
    "required status checks are failing = no",
    "status checks are failing = no",
    "required checks failed = no",
    "required status checks failed = no",
    "status checks failed = no",
    "required checks are failing = false",
    "required status checks are failing = false",
    "status checks are failing = false",
    "required checks failed = false",
    "required status checks failed = false",
    "status checks failed = false",
    "required checks are failing = none",
    "required status checks are failing = none",
    "status checks are failing = none",
    "required checks failed = none",
    "required status checks failed = none",
    "status checks failed = none",
    "required checks are failing - no",
    "required status checks are failing - no",
    "status checks are failing - no",
    "required checks failed - no",
    "required status checks failed - no",
    "status checks failed - no",
    "required checks are failing - false",
    "required status checks are failing - false",
    "status checks are failing - false",
    "required checks failed - false",
    "required status checks failed - false",
    "status checks failed - false",
    "required checks are failing - none",
    "required status checks are failing - none",
    "status checks are failing - none",
    "required checks failed - none",
    "required status checks failed - none",
    "status checks failed - none",
];

pub(in super::super) const FAILURE_CONTEXT: &[&str] =
    &["are failing", "resolved: blocked", "now blocked"];

pub(in super::super) const RESOLVED_BLOCKER: &[&str] = &[
    "blocker resolved",
    "blocker was resolved",
    "previous blocker resolved",
    "previous blocker was resolved",
    "resolved blocker",
    "previously blocked",
    "was blocked",
    "were blocked",
    "had been blocked",
];

pub(in super::super) const RESOLVED_CHECK: &[&str] = &[
    "required checks failed and were fixed",
    "required checks failed and were resolved",
    "required checks failed and were cleared",
    "required status checks failed and were fixed",
    "required status checks failed and were resolved",
    "required status checks failed and were cleared",
    "status checks failed and were fixed",
    "status checks failed and were resolved",
    "status checks failed and were cleared",
    "required checks were fixed",
    "required checks were resolved",
    "required checks were cleared",
    "required status checks were fixed",
    "required status checks were resolved",
    "required status checks were cleared",
    "status checks were fixed",
    "status checks were resolved",
    "status checks were cleared",
];
