#!/bin/sh
set -eu

receipt=$1
test -n "$STAGING_SOURCE_COMMIT"
test -n "$ACTIVATION_COMMIT"
test -n "$STAGING_RUN_ID"
test "$(git rev-parse "$STAGING_SOURCE_COMMIT")" = "$STAGING_SOURCE_COMMIT"
test "$(git rev-parse "$ACTIVATION_COMMIT")" = "$ACTIVATION_COMMIT"
test "$(jq -r .source.stagingSourceCommit "$receipt")" = "$STAGING_SOURCE_COMMIT"
test "$(jq -r .source.activationCommit "$receipt")" = "$ACTIVATION_COMMIT"
test "$(jq -r .staging.runId "$receipt")" = "$STAGING_RUN_ID"
