"""Bounded, trusted-local, single-call MCP scenario execution."""

from .runner import run_single_call
from .support import (
    DEFAULT_PROTOCOL_VERSION,
    DEFAULT_TRANSPORT,
    PLATFORM_LIMITATIONS,
    SDK_TRANSPORT_CHOICE,
    SUPPORTED_PLATFORMS,
    SUPPORTED_PROTOCOL_VERSIONS,
    SUPPORTED_TRANSPORTS,
    TransportSupport,
    runtime_platform,
    supported_versions,
    validate_platform,
    validate_support,
)
from .types import (
    CancellationToken,
    ExecutionError,
    ExecutionResult,
    ExpectedResult,
    ResultKind,
    ScenarioValidationError,
    SingleCall,
    UnsupportedPlatformError,
    UnsupportedProtocolError,
    UnsupportedTransportError,
)

__all__ = [
    "CancellationToken",
    "DEFAULT_PROTOCOL_VERSION",
    "DEFAULT_TRANSPORT",
    "ExecutionError",
    "ExecutionResult",
    "ExpectedResult",
    "PLATFORM_LIMITATIONS",
    "ResultKind",
    "SDK_TRANSPORT_CHOICE",
    "SUPPORTED_PLATFORMS",
    "SUPPORTED_PROTOCOL_VERSIONS",
    "SUPPORTED_TRANSPORTS",
    "ScenarioValidationError",
    "SingleCall",
    "TransportSupport",
    "UnsupportedProtocolError",
    "UnsupportedPlatformError",
    "UnsupportedTransportError",
    "run_single_call",
    "runtime_platform",
    "supported_versions",
    "validate_platform",
    "validate_support",
]
